### ISSUE TITLE
Files that are deleted still shows in session file.

### ISSUE THREAD

**Issue by I-Own-You** [gennaro-tedesco/nvim-possession#26]
I have encountered a issue.

If i delete a file within [ranger](https://github.com/kevinhwang91/rnvimr) plugin in neovim, the session still shows it after loading it the next time, if i update it the same is happening. I tried another session plugin and it behaves the same.

I tried deleting the file within the command line, and then it works as expected.

Here is a video to understand better.

https://github.com/gennaro-tedesco/nvim-possession/assets/91146968/c9135e39-2f42-4158-b8b1-6cee6490d98e

**Comment by gennaro-tedesco** [comment]
After you delete the `1.lua` file with ranger, can you please check whether such buffer still exists in the list of buffers that are in memory and/or as a tab (since when you open it back again it shows as tab I presume you opened it as such, initially)?

Moreover can you try to reproduce the behaviour with both `autosave = true` and `false` (in the latter case, by manually saving the session before exiting)? Does it happen with either parameter being set?

**Comment by I-Own-You** [comment]
> After you delete the `1.lua` file with ranger, can you please check whether such buffer still exists in the list of buffers that are in memory and/or as a tab (since when you open it back again it shows as tab I presume you opened it as such, initially)?
> 
> Moreover can you try to reproduce the behaviour with both `autosave = true` and `false` (in the latter case, by manually saving the session before exiting)? Does it happen with either parameter being set?
> 
> 

Sure, but after 15-20 min, so i arrive at home

**Comment by I-Own-You** [comment]
> After you delete the `1.lua` file with ranger, can you please check whether such buffer still exists in the list of buffers that are in memory and/or as a tab (since when you open it back again it shows as tab I presume you opened it as such, initially)?
> 
> Moreover can you try to reproduce the behaviour with both `autosave = true` and `false` (in the latter case, by manually saving the session before exiting)? Does it happen with either parameter being set?

When i delete 1.lua, it doesnt exist in :buffers.
Both autosave = true/false behave the same, 1.lua still appears in above

When i close the buffer, and then delete it, the buffer then doesnt appear(as expected)

**Comment by gennaro-tedesco** [comment]
> When i delete 1.lua, it doesnt exist in :buffers.

but it does exist as empty buffer in a different tab, does it (in your recording it's shown as opened in a different tab)?

> When i close the buffer, 

what buffer are you referring to here?

The reason I am asking is because I suspect that the ranger plugin you're using may delete the file in your tree view but still preserve it in the current nvim session (just removing its content, and hence as "empty" buffer). What `nvim-possession` does is merely invoking the command `:mksession`, thus you would get the same behaviour by manually saving the sessions (it doesn't really depend on the plugin, but rather on how the ranger file tree deletes files in a vim session).

**Comment by I-Own-You** [comment]
> > When i delete 1.lua, it doesnt exist in :buffers.
> 
> but it does exist as empty buffer in a different tab, doesn't it (in your recording it's shown as opened in a different tab)?
> 
> > When i close the buffer,
> 
> what buffer are you referring to here?
> 
> The reason I am asking is because I suspect that the ranger plugin you're using may delete the file in your tree view but still preserve it in the current nvim session (just removing its content, and hence as "empty" buffer). What `nvim-possession` does is merely invoking the command `:mksession`, thus you would get the same behaviour by manually saving the sessions (it doesn't really depend on the plugin, but rather on how the ranger file tree deletes files in a vim session).

What do you mean a buffer in a different tab ? No, it doesnt exist at all, if it would be in a tab, in the right upper corner i would see that, so it is opened as a buffer.
I am referring to 1.lua.

How it can remain as *empty* buffer if it doesnt exist ?
And when i delete it, the buffer disappears, why would it come back when i load the session on next startup ?

So the problem is not on your side ?

**Comment by gennaro-tedesco** [comment]
> How it can remain as empty buffer if it doesnt exist ?

This depends on what exactly the ranger plugin does: does it completely remove the file from disk, or does it remove the content only whilst preserving the memory location while in a vim session?

This said: in order to determine where the behaviour lies, could you please try to, after deleting the file, manually invoke `:mksession <session name>` and save the session manually? Once so, would the file still be present in such a manually saved session?

**Comment by gennaro-tedesco** [comment]
If the file still appears even by manually saving the session then it means that ranger doesn't really delete the memory buffer :)

As such, this is to be addressed to the ranger plugin rather than the vim session mechanism.

**Comment by I-Own-You** [comment]
Okay, it seems that the file persists even if i dont delete it and just close it, and all files opened in neovim through ranger plugin doesnt go away, they persist in the session, and if i open them with neovim(in this case with fzf-lua :buffers), then i can close them/delete through ranger and they will go away, so the problem is opening newly created files through ranger, this is sick
