### ISSUE TITLE
The autoload setting makes the loaded buffer innactive

### ISSUE THREAD

**Issue by I-Own-You** [gennaro-tedesco/nvim-possession#27]
Hello again! Another issue. I have 3, so ill open them apart for convenience.

When autoload = true in plugin setup, when i enter neovim and the session loads, the file that opens(whatever opens) is somehow innactive, doesnt have the colorscheme, lsp isnt working, so i assume its something related to lazy neovim, the keybinding are in plugins.lua and the setup config is a separate file that i load with init.lua

Keymaps:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/91146968/c662473c-2340-4d31-8e2b-98cd819687d9)

Setup config:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/91146968/ada2df21-c3ab-47e8-bdfd-541ceec812e2)

Init.lua:
![image](https://github.com/gennaro-tedesco/nvim-possession/assets/91146968/d3aab05a-20ab-40af-b383-d521eb031baf)

One way to fix that i use :e and the buffer refreshes

**Comment by gennaro-tedesco** [comment]
This is certainly due to some lazy loading that you have for treesitter and lsp, which most likely load later on some specific events that aren't triggered yet when the session is sourced. Notice that in general `nvim-possession` does nothing except for providing an interface with `fzf-lua` and some sugar mechanisms to operate with sessions, it doesn't really change or do anything on its own: as such, the problems that you see when loading sessions via this plugin would most likely occur even if you would source the sessions manually by yourself. In turn, this implies that they are due to your specific lazy loading.

See [here](https://github.com/gennaro-tedesco/nvim-possession/blob/b0462e6ae05bb48be2d07c3ae19833905137cf20/lua/nvim-possession/utils.lua#L62): autoload essentially sources the session and no more.

> One way to fix that i use :e and the buffer refreshes

this is because `:e` manually re-parses the buffer, forcibly invoking treesitter again.

For reference have a look at my setup: [here is my treesitter](https://github.com/gennaro-tedesco/dotfiles/blob/4d41c3af4cd735ec629bedc8a086a5284a87c522/nvim/init.lua#L51-L77), [here is my fzf-lua](https://github.com/gennaro-tedesco/dotfiles/blob/4d41c3af4cd735ec629bedc8a086a5284a87c522/nvim/init.lua#L215-L251) and [here is nvim-possession](https://github.com/gennaro-tedesco/dotfiles/blob/4d41c3af4cd735ec629bedc8a086a5284a87c522/nvim/init.lua#L378-L397). This setup _does_ work :)
