### ISSUE TITLE
Decouple fzf-lua to a plugin?

### ISSUE THREAD

**Issue by tmpm697** [gennaro-tedesco/nvim-possession#8]
There're many plugins to manage smth called session/project that does the same thing: switch current cwd.

session management plugin will listen on cwd event and eventually does its job without ack of whatever trigger cwd, so fzf-lua support should be decoupled to another plugin.

**Comment by gennaro-tedesco** [comment]
Wouldn't that be too much of an overhead of plugins to install? Namely users will have to install 

1. a session manager (this or some other)
2. a file picker (fzf-lua/Telescope)
3. another plugin that does the coupling between 1. and 2.? (or did I misunderstand)?

Also in that case I am not sure what's the need of a session manager at all, since if all the users want is an autocommand to detect `cwd` they could just write said autocommand in one line of code.

**Comment by tmpm697** [comment]
from my perspective, a session manager manages the session support basic operations like save/auto save/restore. Put that alone there's pretty much of things to add/wrap around mksession like some issues that I created.

other file/directory/project picker is a nice to have feature to a session manager as they do fuzzy and create/select/delete session that another set of function compare to a session manager.

you can feel that there's no need to decouple it as the codebase look compact enough but it'll growing fast with new support features. or i might be wrong.
